### ISSUE TITLE
Server Error (500) on Registration

### ISSUE THREAD

**Issue by AyrtonB** [cogent-computing/COPED#24]
When trying to register an account I get a 500 response error.

I thought this might have been my .xyz email domain but got the same issue with a .com email.

**Comment by AyrtonB** [comment]
Looks like I was using the wrong link (probably the test site?) - http://94.23.203.85/

Working fine with https://coped.coventry.ac.uk/

**Comment by colinstephen** [comment]
Thanks for noting this. It was an old instance I completely forgot about and which Docker kept going. Now shutdown.
